# Generated by Django 5.0.4 on 2024-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created'], name='todo_task_created_09f45e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['done'], name='todo_task_done_bb1940_idx'),
        ),
    ]
