# Generated by Django 5.0.4 on 2024-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_task_todo_task_created_09f45e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'کار', 'verbose_name_plural': 'کار ها'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=300, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='انجام شده'),
        ),
    ]
